### ISSUE TITLE
Package doesn't work in Julia 0.5

### ISSUE THREAD

**Issue by giordano** [stevengj/Cubature.jl#18]
At least since 2016-05-24 (see http://pkg.julialang.org/detail/Cubature.html) this package doesn't work in Julia 0.5.  This is an excerpt from http://pkg.julialang.org/logs/Cubature_0.5.log:

```
ERROR: LoadError: sigatomic_end called in non-sigatomic region
 in cubature(::Bool, ::Bool, ::Bool, ::Bool, ::Int64, ::Function, ::Int64, ::Int64, ::Float64, ::Float64, ::Int64, ::Int32) at /home/vagrant/.julia/v0.5/Cubature/src/Cubature.jl:213
 in #hquadrature#12(::Float64, ::Float64, ::Int64, ::Function, ::Function, ::Int64, ::Int64) at /home/vagrant/.julia/v0.5/Cubature/src/Cubature.jl:227
 in (::Cubature.#kw##hquadrature)(::Array{Any,1}, ::Cubature.#hquadrature, ::Function, ::Int64, ::Int64) at ./null:0
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:266
 in _start() at ./client.jl:322
while loading /home/vagrant/.julia/v0.5/Cubature/test/runtests.jl, in expression starting on line 7
```

**Comment by stevengj** [comment]
@yuyichao, is this due to the changes in JuliaLang/julia#16174?

Cubature is calling `sigatomic_begin` explicitly before the ccall, then `sigatomic_end`/`sigatomic_begin` inside a Julia callback to temporarily re-enable exceptions, then finally `sigatomic_end` after the ccall.   I thought this was still the correct thing to do [according to your comment](https://github.com/JuliaLang/julia/pull/16174#issuecomment-216553403)?

**Comment by yuyichao** [comment]
It should be fine. The sigatomic counter is task local now, does this package use tasks?

**Comment by stevengj** [comment]
No, it doesn't use tasks.

**Comment by yuyichao** [comment]
Briefly looking at code, the issue might be that the counter is resetting in catch

**Comment by stevengj** [comment]
Why would the counter reset, as opposed to just decrement?

**Comment by stevengj** [comment]
I isolated this into a pure Julia example that illustrates the same error, and filed it as JuliaLang/julia#17281
